# -*- coding: utf-8 -*-
"""Project_RPS_ATM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OpceB9pHO8fIDx4cGiyhlxXTAinuW_h7

# Rock Paper Scissor!


> The purpose of this project is for practicing my Python programming skills based on one of popular beginner project "Rock Paper Scissor".

How to start

##### 1. ctrl+enter to run this game.
##### 2. Choose your action "Rock", "Paper", or "Scissor" then press Enter.
##### 3. If you would like to quit the game, type "quit" then press Enter.
<br/>
Thank you for visiting!
"""

# import random
import random

# define rules as dictionary
wins_dict = {
    "rock" : "scissor",
    "scissor" : "paper",
    "paper" : "rock",
    "quit" : "quit"
    }

# define games
def games():
    player_count = 0
    com_count = 0
       
    while True:
        action = ["rock", "paper", "scissor", "quit"]

        player_action = None
        while player_action not in action:
            player_action = input(f"""Choose your action: Scissor, Paper, or Rock?\nType 'quit' to quit the game.\nyour action: """).lower().strip(" ")
        com_action = random.choice(action[0:3])

        if wins_dict[player_action] == com_action:
            print(f"{player_action} VS. {com_action}")
            print("-> You Win!")
            player_count += 1
            print(f"Your score: {player_count}\nComputer score: {com_count}\n-------")
        elif wins_dict[com_action] == player_action:
            print(f"{player_action} VS. {com_action}")
            print("-> You Lose!")
            com_count += 1
            print(f"Your score: {player_count}\nComputer score: {com_count}\n-------")
        elif player_action == com_action:
            print(f"{player_action} VS. {com_action}")
            print("-> Tie")
            print(f"Your score: {player_count}\nComputer score: {com_count}\n-------")
        elif player_action == "quit":
            print(f"Summary Score \n Your score: {player_count}\n Computer score: {com_count}""")
            if player_count > com_count:
                print("Yeah! You Win the game!")
            elif player_count < com_count:
                print("You lose. Try again next time!")
            elif player_count == com_count:
                print("Hmm, We tie.")
            print("Thanks for playing with me :D")
            break
games()
