# -*- coding: utf-8 -*-
"""API_Cov_UK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7tu8wTL964vNP7CoQnb1Ai8Y2-1uo4A

# Coronavirus (COVID-19) in the UK

Using API to get data and make dataframe

Source: https://coronavirus.data.gov.uk/details/developers-guide/main-api
"""

from requests import get
import pandas as pd

url = 'https://api.coronavirus.data.gov.uk/v1/data'

response = get(url)
response.status_code

# View some data in JSON
data = response.json()['data']

data[9]

# Covert values in JSON into list
date = []
areaName = []
areaCode = []
confirmedRate = []
latestBy = []
confirmed = []
deathNew = []
death = []
deathRate = []


length = len(data)

for i in range(length):
    date.append(data[i]['date'])
    areaName.append(data[i]['areaName'])
    areaCode.append(data[i]['areaCode'])
    confirmedRate.append(data[i]['confirmedRate'])
    latestBy.append(data[i]['latestBy'])
    confirmed.append(data[i]['confirmed'])
    deathNew.append(data[i]['deathNew'])
    death.append(data[i]['death'])
    deathRate.append(data[i]['deathRate'])

print(type(date))

# Create Dataframe
uk_covid_df = pd.DataFrame({
    'date': date,
    'areaName': areaName,
    'areaCode': areaCode,
    'confirmedRate': confirmedRate,
    'latestBy': latestBy,
    'confirmed': confirmed,
    'deathNew': deathNew,
    'death': death,
    'deathRate': deathRate
})

# Preview Dataframe
uk_covid_df.head()

# Preview Dataframe's shape (rows, columns)
uk_covid_df.shape

# Check missing values from each columns
uk_covid_df.isna().sum()

# Plot to view some infomation
cf_case_plot = uk_covid_df.sort_values('date').reset_index()\
    .plot(kind='line', figsize=[9, 6], x='date', y='latestBy',\
          color={'latestBy': 'blue'})