# -*- coding: utf-8 -*-
"""ATM_OOP_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJqp734nkyiRmo7BU_GD8adC5b1lHYOR

# ATM project


> The purpose of this project is for practicing the Object Oriented Programmaing in Python. The project was simply automated teller machine (ATM) programming.

There are five developed methods.
- Check your account details
- Balance check
- Deposit
- Withdraw
- Transfer

Thank you for visiting!
"""

class atm:
    def __init__(self, acc_num, name, bank, branch, balance):
        self.acc_num = acc_num
        self.name = name
        self.bank = bank
        self.branch = branch
        self.balance = balance
    def __str__(self):
        return "ATM class & methods"
        
    def acc_detail(self):
        print(f"This is your account information\n Name: {self.name}\n Account Number: {self.acc_num}\n Bank: {self.bank}\n Branch: {self.branch}")

    def balance_check(self):
        print(f"---Balance---\nAccount Number: {self.acc_num}\nBalance: {self.balance} THB")

    def deposit(self, dep_amount):
        self.balance += dep_amount
        print(f"Deposit Successful, your balance is: {self.balance} THB")
    
    def withdraw(self, wit_amount):
        self.balance -= wit_amount
        print(f"Withdraw Successful, your balance is: {self.balance} THB")

    def transfer(self, rec_acc_num, tran_amount):
        self.balance -= tran_amount
        print(f"Recipient Account Number: {(rec_acc_num)}\nAmount: {tran_amount} THB\n-----\nTransfer Sucessful, your balance is: {self.balance} THB")

# create instances
user1 = atm("111-1111", "Amy Whitaker", "In your Dream bank", "Bangkok", 50000)
user2 = atm("222-2222", "Sara Magistus", "Not Real bank", "Bangkok", 120000)
user3 = atm("333-3333", "Kazoo Bazooka", "Not Real bank", "Hua Hin", 35000)

user2.acc_detail()

user3.balance_check()

user1.deposit(1000)

user1.withdraw(1000)

user1.transfer("555-5555", 3000)